### ISSUE TITLE
ISSUE: Sensors not available

### ISSUE THREAD

**Issue by bcskillings** [FutureTense/keymaster#134]
**Describe the bug**
The Lovelace card gives three errors per lock code, where x equals the code number

Entity not available: sensor.connected_front_door_x
Entity not available: binary_sensor.active_front_door_x
Entity not available: binary_sensor.pin_synched_front_door_x

**Environment (please complete the following information):**

- OS: HassOS
- Type of device: RPi3b+
- Home Assistant version: core-2021.3.4, 
- Hassio/Docker/Core? Core
- Component version: 0.0.27

**Logs**
<details><summary>Logs</summary>
2021-03-16 06:28:07 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-16 06:28:26 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2021-03-16 06:28:26 WARNING (MainThread) [homeassistant.setup] Setup of group is taking over 10 seconds.
2021-03-16 06:28:26 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2021-03-16 06:28:26 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2021-03-16 06:28:26 WARNING (MainThread) [homeassistant.setup] Setup of media_source is taking over 10 seconds.
2021-03-16 06:28:26 WARNING (MainThread) [homeassistant.components.scene] Setup of scene platform homeassistant is taking over 10 seconds.
2021-03-16 06:28:26 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2021-03-16 06:28:39 WARNING (MainThread) [homeassistant.loader] You are using a custom integration keymaster which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-16 06:28:51 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
return await self._handle_request(request, token, path)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
source_header = _init_header(request, token)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 189, in _init_header
connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-03-16 06:28:53 WARNING (MainThread) [homeassistant.components.frontend] Theme ios-light-mode-unknown not found
2021-03-16 06:33:13 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
return await self._handle_request(request, token, path)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
source_header = _init_header(request, token)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 189, in _init_header
connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-03-16 06:33:14 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
return await self._handle_request(request, token, path)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
source_header = _init_header(request, token)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 189, in _init_header
connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-03-16 06:47:10 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
return await self._handle_request(request, token, path)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
source_header = _init_header(request, token)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 189, in _init_header
connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
2021-03-16 07:07:52 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
return await self._handle_request(request, token, path)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 121, in _handle_request
source_header = _init_header(request, token)
File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 189, in _init_header
connected_ip = ip_address(request.transport.get_extra_info("peername")[0])
TypeError: 'NoneType' object is not subscriptable
</details>
**Screenshots**

![Screenshot from 2021-03-16 07-10-30](https://user-images.githubusercontent.com/31419498/111308976-5901bf80-8629-11eb-8e06-c3f36b3bfc74.png)

**Additional context**
Lovelace code:
<details><summary>Lovelace Code</summary>
```yaml
  - title: 'front_door Codes and Configuration'
    path: keypad-front_door
    icon: 'mdi:lock-smart'
    panel: false
    badges:
      - input_boolean.front_door_dooraccess_notifications
      - entity: >-
          lock.front_door_lock
      - entity: >-
          binary_sensor.front_door_ias_zone
    cards:
      - type: vertical-stack
        cards:
          - content: |
              ## Code 1
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_1
              - entity: input_text.front_door_pin_1
              - entity: input_boolean.enabled_front_door_1
              - entity: input_boolean.notify_front_door_1
              - type: divider
              - entity: sensor.connected_front_door_1
                state_color: true
              - entity: binary_sensor.active_front_door_1
                state_color: true
              - entity: binary_sensor.pin_synched_front_door_1
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_1
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_1
                  - entity: input_number.accesscount_front_door_1
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_1
                  - entity: input_datetime.start_date_front_door_1
                  - entity: input_datetime.end_date_front_door_1
                  - type: divider
                  - input_boolean.sun_front_door_1
                  - input_boolean.sun_inc_front_door_1
                  - input_datetime.sun_start_date_front_door_1
                  - input_datetime.sun_end_date_front_door_1
                  - type: divider
                  - input_boolean.mon_front_door_1
                  - input_boolean.mon_inc_front_door_1
                  - input_datetime.mon_start_date_front_door_1
                  - input_datetime.mon_end_date_front_door_1
                  - type: divider
                  - input_boolean.tue_front_door_1
                  - input_boolean.tue_inc_front_door_1
                  - input_datetime.tue_start_date_front_door_1
                  - input_datetime.tue_end_date_front_door_1
                  - type: divider
                  - input_boolean.wed_front_door_1
                  - input_boolean.wed_inc_front_door_1
                  - input_datetime.wed_start_date_front_door_1
                  - input_datetime.wed_end_date_front_door_1
                  - type: divider
                  - input_boolean.thu_front_door_1
                  - input_boolean.thu_inc_front_door_1
                  - input_datetime.thu_start_date_front_door_1
                  - input_datetime.thu_end_date_front_door_1
                  - type: divider
                  - input_boolean.fri_front_door_1
                  - input_boolean.fri_inc_front_door_1
                  - input_datetime.fri_start_date_front_door_1
                  - input_datetime.fri_end_date_front_door_1
                  - type: divider
                  - input_boolean.sat_front_door_1
                  - input_boolean.sat_inc_front_door_1
                  - input_datetime.sat_start_date_front_door_1
                  - input_datetime.sat_end_date_front_door_1
      - type: vertical-stack
        cards:
          - content: |
              ## Code 2
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_2
              - entity: input_text.front_door_pin_2
              - entity: input_boolean.enabled_front_door_2
              - entity: input_boolean.notify_front_door_2
              - type: divider
              - entity: sensor.connected_front_door_2
                state_color: true
              - entity: binary_sensor.active_front_door_2
                state_color: true
              - entity: binary_sensor.pin_synched_front_door_2
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_2
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_2
                  - entity: input_number.accesscount_front_door_2
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_2
                  - entity: input_datetime.start_date_front_door_2
                  - entity: input_datetime.end_date_front_door_2
                  - type: divider
                  - input_boolean.sun_front_door_2
                  - input_boolean.sun_inc_front_door_2
                  - input_datetime.sun_start_date_front_door_2
                  - input_datetime.sun_end_date_front_door_2
                  - type: divider
                  - input_boolean.mon_front_door_2
                  - input_boolean.mon_inc_front_door_2
                  - input_datetime.mon_start_date_front_door_2
                  - input_datetime.mon_end_date_front_door_2
                  - type: divider
                  - input_boolean.tue_front_door_2
                  - input_boolean.tue_inc_front_door_2
                  - input_datetime.tue_start_date_front_door_2
                  - input_datetime.tue_end_date_front_door_2
                  - type: divider
                  - input_boolean.wed_front_door_2
                  - input_boolean.wed_inc_front_door_2
                  - input_datetime.wed_start_date_front_door_2
                  - input_datetime.wed_end_date_front_door_2
                  - type: divider
                  - input_boolean.thu_front_door_2
                  - input_boolean.thu_inc_front_door_2
                  - input_datetime.thu_start_date_front_door_2
                  - input_datetime.thu_end_date_front_door_2
                  - type: divider
                  - input_boolean.fri_front_door_2
                  - input_boolean.fri_inc_front_door_2
                  - input_datetime.fri_start_date_front_door_2
                  - input_datetime.fri_end_date_front_door_2
                  - type: divider
                  - input_boolean.sat_front_door_2
                  - input_boolean.sat_inc_front_door_2
                  - input_datetime.sat_start_date_front_door_2
                  - input_datetime.sat_end_date_front_door_2
      - type: vertical-stack
        cards:
          - content: |
              ## Code 3
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_3
              - entity: input_text.front_door_pin_3
              - entity: input_boolean.enabled_front_door_3
              - entity: input_boolean.notify_front_door_3
              - type: divider
              - entity: sensor.connected_front_door_3
                state_color: true
              - entity: binary_sensor.active_front_door_3
                state_color: true
              - entity: binary_sensor.pin_synched_front_door_3
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_3
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_3
                  - entity: input_number.accesscount_front_door_3
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_3
                  - entity: input_datetime.start_date_front_door_3
                  - entity: input_datetime.end_date_front_door_3
                  - type: divider
                  - input_boolean.sun_front_door_3
                  - input_boolean.sun_inc_front_door_3
                  - input_datetime.sun_start_date_front_door_3
                  - input_datetime.sun_end_date_front_door_3
                  - type: divider
                  - input_boolean.mon_front_door_3
                  - input_boolean.mon_inc_front_door_3
                  - input_datetime.mon_start_date_front_door_3
                  - input_datetime.mon_end_date_front_door_3
                  - type: divider
                  - input_boolean.tue_front_door_3
                  - input_boolean.tue_inc_front_door_3
                  - input_datetime.tue_start_date_front_door_3
                  - input_datetime.tue_end_date_front_door_3
                  - type: divider
                  - input_boolean.wed_front_door_3
                  - input_boolean.wed_inc_front_door_3
                  - input_datetime.wed_start_date_front_door_3
                  - input_datetime.wed_end_date_front_door_3
                  - type: divider
                  - input_boolean.thu_front_door_3
                  - input_boolean.thu_inc_front_door_3
                  - input_datetime.thu_start_date_front_door_3
                  - input_datetime.thu_end_date_front_door_3
                  - type: divider
                  - input_boolean.fri_front_door_3
                  - input_boolean.fri_inc_front_door_3
                  - input_datetime.fri_start_date_front_door_3
                  - input_datetime.fri_end_date_front_door_3
                  - type: divider
                  - input_boolean.sat_front_door_3
                  - input_boolean.sat_inc_front_door_3
                  - input_datetime.sat_start_date_front_door_3
                  - input_datetime.sat_end_date_front_door_3
      - type: vertical-stack
        cards:
          - content: |
              ## Code 4
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_4
              - entity: input_text.front_door_pin_4
              - entity: input_boolean.enabled_front_door_4
              - entity: input_boolean.notify_front_door_4
              - type: divider
              - entity: sensor.connected_front_door_4
                state_color: true
              - entity: binary_sensor.active_front_door_4
                state_color: true
              - entity: binary_sensor.pin_synched_front_door_4
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_4
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_4
                  - entity: input_number.accesscount_front_door_4
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_4
                  - entity: input_datetime.start_date_front_door_4
                  - entity: input_datetime.end_date_front_door_4
                  - type: divider
                  - input_boolean.sun_front_door_4
                  - input_boolean.sun_inc_front_door_4
                  - input_datetime.sun_start_date_front_door_4
                  - input_datetime.sun_end_date_front_door_4
                  - type: divider
                  - input_boolean.mon_front_door_4
                  - input_boolean.mon_inc_front_door_4
                  - input_datetime.mon_start_date_front_door_4
                  - input_datetime.mon_end_date_front_door_4
                  - type: divider
                  - input_boolean.tue_front_door_4
                  - input_boolean.tue_inc_front_door_4
                  - input_datetime.tue_start_date_front_door_4
                  - input_datetime.tue_end_date_front_door_4
                  - type: divider
                  - input_boolean.wed_front_door_4
                  - input_boolean.wed_inc_front_door_4
                  - input_datetime.wed_start_date_front_door_4
                  - input_datetime.wed_end_date_front_door_4
                  - type: divider
                  - input_boolean.thu_front_door_4
                  - input_boolean.thu_inc_front_door_4
                  - input_datetime.thu_start_date_front_door_4
                  - input_datetime.thu_end_date_front_door_4
                  - type: divider
                  - input_boolean.fri_front_door_4
                  - input_boolean.fri_inc_front_door_4
                  - input_datetime.fri_start_date_front_door_4
                  - input_datetime.fri_end_date_front_door_4
                  - type: divider
                  - input_boolean.sat_front_door_4
                  - input_boolean.sat_inc_front_door_4
                  - input_datetime.sat_start_date_front_door_4
                  - input_datetime.sat_end_date_front_door_4
```
</details>
