### ISSUE TITLE
[Feature Request] Update Lock Notification and User Notification Automations to Prevent Duplicate Messages on Pin Unlock Events

### ISSUE THREAD

**Issue by Xero-Cool** [FutureTense/keymaster#150]
**Is your feature request related to a problem? Please describe.**
The action for the "CASE_LOCK_NAME Lock Notifications" and "CASE_LOCK_NAME User Notifications" automations (calls script.LOCKNAME_manual_notify) can both be triggered if both respective input booleans are enabled, resulting in duplicate notifications for a single pin unlock event. Additionally, the messaging for the "CASE_LOCK_NAME Lock Notifications" automation can be improved to provide the pin slot name if a pin is used. 

**Describe the solution you'd like**
Add a condition to the "CASE_LOCK_NAME User Notifications" automation such that the action is only triggered if the "input_boolean.LOCKNAME_lock_notifications" state is "off". Add a conditional statement to the message in the "CASE_LOCK_NAME Lock Notifications" such that it will display the pin slot name if the door was unlocked with a pin.

This way, "CASE_LOCK_NAME Lock Notifications" takes precedence over "CASE_LOCK_NAME User Notifications" if both are enabled, and "CASE_LOCK_NAME Lock Notifications" will send a notification message with the pin slot name included if a pin was used to unlock the door.

**Describe alternatives you've considered**
```yaml
  - alias: CASE_LOCK_NAME Lock Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: LOCKNAME
    condition:
      - condition: state
        entity_id: input_boolean.LOCKNAME_lock_notifications
        state: "on"
    action:
      - service: script.LOCKNAME_manual_notify
        data_template:
          title: CASE_LOCK_NAME
          message: "{{ trigger.event.data.action_text }}{% if trigger.event.data.code_slot > 0 %} ({{ trigger.event.data.code_slot_name }}){% endif %}"

  - alias: CASE_LOCK_NAME User Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: LOCKNAME
    condition:
      - condition: state
        entity_id: input_boolean.LOCKNAME_lock_notifications
        state: "off"
      - condition: template
        value_template: "{{ trigger.event.data.code_slot > 0 }}"
      - condition: template
        value_template: "{{ is_state('input_boolean.notify_LOCKNAME_' + trigger.event.data.code_slot | string, 'on') }}"
    action:
      - service: script.LOCKNAME_manual_notify
        data_template:
          title: CASE_LOCK_NAME
          message: "{{ trigger.event.data.action_text }} ({{ trigger.event.data.code_slot_name }})" 
```

**Additional context**
