### ISSUE TITLE
ISSUE: child locks not working

### ISSUE THREAD

**Issue by libots** [FutureTense/keymaster#157]
**Describe the bug**
Child lock isn't working. When creating the integration, the YAML file is recognized, but the integration fails to create the child lock or handle it at all in the generated package files. Additionally, when going back into options, the "path to child locks file" is empty.

**Environment (please complete the following information):**

- OS: HA docker container
- Type of system that HA is running on: NUC (Debian VM docker container)
- Home Assistant version: 2021.4.6
- Docker
- Component version: 0.0.31
- Z-Wave integration name: zwave_js
- Lock make and model: Yale YRD256 (master) and YRD226 (child)

**Logs**
No errors are generated on debug mode *unless* I try to specify a `door_sensor_entity_id` (I tried that after some googling, but it gives `ERROR (SyncWorker_35) [custom_components.keymaster.config_flow] Child locks file data is invalid: extra keys not allowed @ data['back_child']['door_sensor_entity_id']`).

**Additional context**
My child file:
```yaml
back_child:
  lock_entity_id: lock.back
  # door_sensor_entity_id: binary_sensor.door_back_homekit
  alarm_level_or_user_code_entity_id: sensor.fake
  alarm_type_or_access_control_entity_id: sensor.fake
```
