### ISSUE TITLE
ISSUE: Schlage FE599 Door check

### ISSUE THREAD

**Issue by lishan89uc** [FutureTense/keymaster#234]
**Describe the bug**
For some locks such as Schlage FE599nx Lever lock the door status is always open since the lock can't detect open or close. However with this issue the auto lock feature stops working. It will just keep resetting to 30 secs

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on:  RPi4
- Home Assistant version: core-2021.10.0
- Hassio
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: zwave_js
- Lock make and model: Schalge fe599nx

**Logs**

**Screenshots**

**Additional context**
Can we add a way to turn off the door status check?
right now what i did was delete the check from the packages
```
 - alias: keymaster_front_door_timer_finished
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.keymaster_front_door_autolock
    action:
      - service: lock.lock
        entity_id: lock.front_door
```
