### ISSUE TITLE
[Feature Request] Do you want me to add GitHub actions?

### ISSUE THREAD

**Issue by KTibow** [FutureTense/keymaster#3]
*Sorry for not following the issue template*

If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by firstof9** [comment]
I was planning to change the formatting.yaml to the following:

```yaml
name: Validate with hassfest

on:
  push:
  pull_request: ~

jobs:
  formatting:
    name: Formatting Check
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.x"
      - run: python3 -m pip install black
      - run: black .

  validate:
    name: Validate component
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: HACS validation
        uses: "hacs/integration/action@master"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY: "integration"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
```
I just haven't gotten to it yet, but feel free to send a PR :)
