### ISSUE TITLE
ISSUE: Custom element doesn't exist: fold-entity-row in Dashboard

### ISSUE THREAD

**Issue by shrowner** [FutureTense/keymaster#313]
**Describe the bug**
Dashboard does not work throwing "Custom element doesn't exist: fold-entity-row" error

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/19720088/209068697-c345605d-856a-45f6-8735-efc55c13e984.png">

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: Mac Mini
- Home Assistant version: Home Assistant 2022.12.1
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221208.0 - latest
- Component version: v0.0.82
- Z-Wave integration name: zwave_js
- Lock make and model: Kwikset 910

**Logs**
YAML output from /config/packages/keymaster/back_door_look/back_door_look_lovelace

  - title: 'back_door_look Codes and Configuration'
    path: keypad-back_door_look
    icon: 'mdi:lock-smart'
    panel: false
    badges:
      - input_text.back_door_look_lockname
      - input_boolean.back_door_look_lock_notifications
      - input_boolean.back_door_look_dooraccess_notifications
      - input_boolean.back_door_look_garageacess_notifications
      - entity: >-
          lock.back_door_lock
      - entity: >-
          binary_sensor.fake
      - entity: input_text.keymaster_back_door_look_autolock_door_time_day
      - entity: input_text.keymaster_back_door_look_autolock_door_time_night
      - entity: input_boolean.keymaster_back_door_look_autolock
      - entity: timer.keymaster_back_door_look_autolock
    cards:
      - type: vertical-stack
        cards:
          - content: |
              ## Code 1
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.back_door_look_name_1
              - entity: input_text.back_door_look_pin_1
              - entity: input_boolean.enabled_back_door_look_1
              - entity: input_boolean.notify_back_door_look_1
              - type: divider
              - entity: sensor.connected_back_door_look_1
                state_color: true
              - entity: binary_sensor.active_back_door_look_1
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_back_door_look_1
                  - type: divider
                  - entity: input_boolean.accesslimit_back_door_look_1
                  - entity: input_number.accesscount_back_door_look_1
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_back_door_look_1
                  - entity: input_datetime.start_date_back_door_look_1
                  - entity: input_datetime.end_date_back_door_look_1
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_back_door_look_1
                      - input_boolean.sun_inc_back_door_look_1
                      - input_datetime.sun_start_date_back_door_look_1
                      - input_datetime.sun_end_date_back_door_look_1
                      - type: divider
                      - input_boolean.mon_back_door_look_1
                      - input_boolean.mon_inc_back_door_look_1
                      - input_datetime.mon_start_date_back_door_look_1
                      - input_datetime.mon_end_date_back_door_look_1
                      - type: divider
                      - input_boolean.tue_back_door_look_1
                      - input_boolean.tue_inc_back_door_look_1
                      - input_datetime.tue_start_date_back_door_look_1
                      - input_datetime.tue_end_date_back_door_look_1
                      - type: divider
                      - input_boolean.wed_back_door_look_1
                      - input_boolean.wed_inc_back_door_look_1
                      - input_datetime.wed_start_date_back_door_look_1
                      - input_datetime.wed_end_date_back_door_look_1
                      - type: divider
                      - input_boolean.thu_back_door_look_1
                      - input_boolean.thu_inc_back_door_look_1
                      - input_datetime.thu_start_date_back_door_look_1
                      - input_datetime.thu_end_date_back_door_look_1
                      - type: divider
                      - input_boolean.fri_back_door_look_1
                      - input_boolean.fri_inc_back_door_look_1
                      - input_datetime.fri_start_date_back_door_look_1
                      - input_datetime.fri_end_date_back_door_look_1
                      - type: divider
                      - input_boolean.sat_back_door_look_1
                      - input_boolean.sat_inc_back_door_look_1
                      - input_datetime.sat_start_date_back_door_look_1
                      - input_datetime.sat_end_date_back_door_look_1
      - type: vertical-stack
        cards:
          - content: |
              ## Code 2
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.back_door_look_name_2
              - entity: input_text.back_door_look_pin_2
              - entity: input_boolean.enabled_back_door_look_2
              - entity: input_boolean.notify_back_door_look_2
              - type: divider
              - entity: sensor.connected_back_door_look_2
                state_color: true
              - entity: binary_sensor.active_back_door_look_2
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_back_door_look_2
                  - type: divider
                  - entity: input_boolean.accesslimit_back_door_look_2
                  - entity: input_number.accesscount_back_door_look_2
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_back_door_look_2
                  - entity: input_datetime.start_date_back_door_look_2
                  - entity: input_datetime.end_date_back_door_look_2
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_back_door_look_2
                      - input_boolean.sun_inc_back_door_look_2
                      - input_datetime.sun_start_date_back_door_look_2
                      - input_datetime.sun_end_date_back_door_look_2
                      - type: divider
                      - input_boolean.mon_back_door_look_2
                      - input_boolean.mon_inc_back_door_look_2
                      - input_datetime.mon_start_date_back_door_look_2
                      - input_datetime.mon_end_date_back_door_look_2
                      - type: divider
                      - input_boolean.tue_back_door_look_2
                      - input_boolean.tue_inc_back_door_look_2
                      - input_datetime.tue_start_date_back_door_look_2
                      - input_datetime.tue_end_date_back_door_look_2
                      - type: divider
                      - input_boolean.wed_back_door_look_2
                      - input_boolean.wed_inc_back_door_look_2
                      - input_datetime.wed_start_date_back_door_look_2
                      - input_datetime.wed_end_date_back_door_look_2
                      - type: divider
                      - input_boolean.thu_back_door_look_2
                      - input_boolean.thu_inc_back_door_look_2
                      - input_datetime.thu_start_date_back_door_look_2
                      - input_datetime.thu_end_date_back_door_look_2
                      - type: divider
                      - input_boolean.fri_back_door_look_2
                      - input_boolean.fri_inc_back_door_look_2
                      - input_datetime.fri_start_date_back_door_look_2
                      - input_datetime.fri_end_date_back_door_look_2
                      - type: divider
                      - input_boolean.sat_back_door_look_2
                      - input_boolean.sat_inc_back_door_look_2
                      - input_datetime.sat_start_date_back_door_look_2
                      - input_datetime.sat_end_date_back_door_look_2
      - type: vertical-stack
        cards:
          - content: |
              ## Code 3
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.back_door_look_name_3
              - entity: input_text.back_door_look_pin_3
              - entity: input_boolean.enabled_back_door_look_3
              - entity: input_boolean.notify_back_door_look_3
              - type: divider
              - entity: sensor.connected_back_door_look_3
                state_color: true
              - entity: binary_sensor.active_back_door_look_3
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_back_door_look_3
                  - type: divider
                  - entity: input_boolean.accesslimit_back_door_look_3
                  - entity: input_number.accesscount_back_door_look_3
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_back_door_look_3
                  - entity: input_datetime.start_date_back_door_look_3
                  - entity: input_datetime.end_date_back_door_look_3
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_back_door_look_3
                      - input_boolean.sun_inc_back_door_look_3
                      - input_datetime.sun_start_date_back_door_look_3
                      - input_datetime.sun_end_date_back_door_look_3
                      - type: divider
                      - input_boolean.mon_back_door_look_3
                      - input_boolean.mon_inc_back_door_look_3
                      - input_datetime.mon_start_date_back_door_look_3
                      - input_datetime.mon_end_date_back_door_look_3
                      - type: divider
                      - input_boolean.tue_back_door_look_3
                      - input_boolean.tue_inc_back_door_look_3
                      - input_datetime.tue_start_date_back_door_look_3
                      - input_datetime.tue_end_date_back_door_look_3
                      - type: divider
                      - input_boolean.wed_back_door_look_3
                      - input_boolean.wed_inc_back_door_look_3
                      - input_datetime.wed_start_date_back_door_look_3
                      - input_datetime.wed_end_date_back_door_look_3
                      - type: divider
                      - input_boolean.thu_back_door_look_3
                      - input_boolean.thu_inc_back_door_look_3
                      - input_datetime.thu_start_date_back_door_look_3
                      - input_datetime.thu_end_date_back_door_look_3
                      - type: divider
                      - input_boolean.fri_back_door_look_3
                      - input_boolean.fri_inc_back_door_look_3
                      - input_datetime.fri_start_date_back_door_look_3
                      - input_datetime.fri_end_date_back_door_look_3
                      - type: divider
                      - input_boolean.sat_back_door_look_3
                      - input_boolean.sat_inc_back_door_look_3
                      - input_datetime.sat_start_date_back_door_look_3
                      - input_datetime.sat_end_date_back_door_look_3

**Screenshots**

Dashboard
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/19720088/209067393-81f0b389-e4b9-4d43-bbfc-43ae172d255c.png">

Frontend from HACS
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/19720088/209067699-2f49befe-7a66-4378-8b6d-b8dc9651bf46.png">

**Comment by shrowner** [comment]
<img width="1677" alt="Overview_–_Home_Assistant" src="https://user-images.githubusercontent.com/19720088/209068886-c35d7884-0641-421e-8e8c-c1a144273f07.png">

**Comment by firstof9** [comment]
Press F5

**Comment by anthonymag** [comment]
Hi there, I am having the same issue. I have restarted Home Assistant and tried refreshing, and tried on a separate device.

OS: Container
Type of system that HA is running on: Ubuntu Server
Home Assistant version: 20230104.0
Z-Wave integration name: zwave_js
Lock make and model: Kwikset 620

front_door_lovelace:
```
  - title: 'front_door Codes and Configuration'
    path: keypad-front_door
    icon: 'mdi:lock-smart'
    panel: false
    badges:
      - input_text.front_door_lockname
      - input_boolean.front_door_lock_notifications
      - input_boolean.front_door_dooraccess_notifications
      - input_boolean.front_door_garageacess_notifications
      - entity: >-
          lock.front_door
      - entity: >-
          binary_sensor.fake
      - entity: input_text.keymaster_front_door_autolock_door_time_day
      - entity: input_text.keymaster_front_door_autolock_door_time_night
      - entity: input_boolean.keymaster_front_door_autolock
      - entity: timer.keymaster_front_door_autolock
    cards:
      - type: vertical-stack
        cards:
          - content: |
              ## Code 1
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_1
              - entity: input_text.front_door_pin_1
              - entity: input_boolean.enabled_front_door_1
              - entity: input_boolean.notify_front_door_1
              - type: divider
              - entity: sensor.connected_front_door_1
                state_color: true
              - entity: binary_sensor.active_front_door_1
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_1
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_1
                  - entity: input_number.accesscount_front_door_1
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_1
                  - entity: input_datetime.start_date_front_door_1
                  - entity: input_datetime.end_date_front_door_1
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_front_door_1
                      - input_boolean.sun_inc_front_door_1
                      - input_datetime.sun_start_date_front_door_1
                      - input_datetime.sun_end_date_front_door_1
                      - type: divider
                      - input_boolean.mon_front_door_1
                      - input_boolean.mon_inc_front_door_1
                      - input_datetime.mon_start_date_front_door_1
                      - input_datetime.mon_end_date_front_door_1
                      - type: divider
                      - input_boolean.tue_front_door_1
                      - input_boolean.tue_inc_front_door_1
                      - input_datetime.tue_start_date_front_door_1
                      - input_datetime.tue_end_date_front_door_1
                      - type: divider
                      - input_boolean.wed_front_door_1
                      - input_boolean.wed_inc_front_door_1
                      - input_datetime.wed_start_date_front_door_1
                      - input_datetime.wed_end_date_front_door_1
                      - type: divider
                      - input_boolean.thu_front_door_1
                      - input_boolean.thu_inc_front_door_1
                      - input_datetime.thu_start_date_front_door_1
                      - input_datetime.thu_end_date_front_door_1
                      - type: divider
                      - input_boolean.fri_front_door_1
                      - input_boolean.fri_inc_front_door_1
                      - input_datetime.fri_start_date_front_door_1
                      - input_datetime.fri_end_date_front_door_1
                      - type: divider
                      - input_boolean.sat_front_door_1
                      - input_boolean.sat_inc_front_door_1
                      - input_datetime.sat_start_date_front_door_1
                      - input_datetime.sat_end_date_front_door_1
      - type: vertical-stack
        cards:
          - content: |
              ## Code 2
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_2
              - entity: input_text.front_door_pin_2
              - entity: input_boolean.enabled_front_door_2
              - entity: input_boolean.notify_front_door_2
              - type: divider
              - entity: sensor.connected_front_door_2
                state_color: true
              - entity: binary_sensor.active_front_door_2
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_2
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_2
                  - entity: input_number.accesscount_front_door_2
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_2
                  - entity: input_datetime.start_date_front_door_2
                  - entity: input_datetime.end_date_front_door_2
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_front_door_2
                      - input_boolean.sun_inc_front_door_2
                      - input_datetime.sun_start_date_front_door_2
                      - input_datetime.sun_end_date_front_door_2
                      - type: divider
                      - input_boolean.mon_front_door_2
                      - input_boolean.mon_inc_front_door_2
                      - input_datetime.mon_start_date_front_door_2
                      - input_datetime.mon_end_date_front_door_2
                      - type: divider
                      - input_boolean.tue_front_door_2
                      - input_boolean.tue_inc_front_door_2
                      - input_datetime.tue_start_date_front_door_2
                      - input_datetime.tue_end_date_front_door_2
                      - type: divider
                      - input_boolean.wed_front_door_2
                      - input_boolean.wed_inc_front_door_2
                      - input_datetime.wed_start_date_front_door_2
                      - input_datetime.wed_end_date_front_door_2
                      - type: divider
                      - input_boolean.thu_front_door_2
                      - input_boolean.thu_inc_front_door_2
                      - input_datetime.thu_start_date_front_door_2
                      - input_datetime.thu_end_date_front_door_2
                      - type: divider
                      - input_boolean.fri_front_door_2
                      - input_boolean.fri_inc_front_door_2
                      - input_datetime.fri_start_date_front_door_2
                      - input_datetime.fri_end_date_front_door_2
                      - type: divider
                      - input_boolean.sat_front_door_2
                      - input_boolean.sat_inc_front_door_2
                      - input_datetime.sat_start_date_front_door_2
                      - input_datetime.sat_end_date_front_door_2
      - type: vertical-stack
        cards:
          - content: |
              ## Code 3
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_3
              - entity: input_text.front_door_pin_3
              - entity: input_boolean.enabled_front_door_3
              - entity: input_boolean.notify_front_door_3
              - type: divider
              - entity: sensor.connected_front_door_3
                state_color: true
              - entity: binary_sensor.active_front_door_3
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_3
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_3
                  - entity: input_number.accesscount_front_door_3
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_3
                  - entity: input_datetime.start_date_front_door_3
                  - entity: input_datetime.end_date_front_door_3
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_front_door_3
                      - input_boolean.sun_inc_front_door_3
                      - input_datetime.sun_start_date_front_door_3
                      - input_datetime.sun_end_date_front_door_3
                      - type: divider
                      - input_boolean.mon_front_door_3
                      - input_boolean.mon_inc_front_door_3
                      - input_datetime.mon_start_date_front_door_3
                      - input_datetime.mon_end_date_front_door_3
                      - type: divider
                      - input_boolean.tue_front_door_3
                      - input_boolean.tue_inc_front_door_3
                      - input_datetime.tue_start_date_front_door_3
                      - input_datetime.tue_end_date_front_door_3
                      - type: divider
                      - input_boolean.wed_front_door_3
                      - input_boolean.wed_inc_front_door_3
                      - input_datetime.wed_start_date_front_door_3
                      - input_datetime.wed_end_date_front_door_3
                      - type: divider
                      - input_boolean.thu_front_door_3
                      - input_boolean.thu_inc_front_door_3
                      - input_datetime.thu_start_date_front_door_3
                      - input_datetime.thu_end_date_front_door_3
                      - type: divider
                      - input_boolean.fri_front_door_3
                      - input_boolean.fri_inc_front_door_3
                      - input_datetime.fri_start_date_front_door_3
                      - input_datetime.fri_end_date_front_door_3
                      - type: divider
                      - input_boolean.sat_front_door_3
                      - input_boolean.sat_inc_front_door_3
                      - input_datetime.sat_start_date_front_door_3
                      - input_datetime.sat_end_date_front_door_3
      - type: vertical-stack
        cards:
          - content: |
              ## Code 4
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_4
              - entity: input_text.front_door_pin_4
              - entity: input_boolean.enabled_front_door_4
              - entity: input_boolean.notify_front_door_4
              - type: divider
              - entity: sensor.connected_front_door_4
                state_color: true
              - entity: binary_sensor.active_front_door_4
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_4
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_4
                  - entity: input_number.accesscount_front_door_4
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_4
                  - entity: input_datetime.start_date_front_door_4
                  - entity: input_datetime.end_date_front_door_4
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_front_door_4
                      - input_boolean.sun_inc_front_door_4
                      - input_datetime.sun_start_date_front_door_4
                      - input_datetime.sun_end_date_front_door_4
                      - type: divider
                      - input_boolean.mon_front_door_4
                      - input_boolean.mon_inc_front_door_4
                      - input_datetime.mon_start_date_front_door_4
                      - input_datetime.mon_end_date_front_door_4
                      - type: divider
                      - input_boolean.tue_front_door_4
                      - input_boolean.tue_inc_front_door_4
                      - input_datetime.tue_start_date_front_door_4
                      - input_datetime.tue_end_date_front_door_4
                      - type: divider
                      - input_boolean.wed_front_door_4
                      - input_boolean.wed_inc_front_door_4
                      - input_datetime.wed_start_date_front_door_4
                      - input_datetime.wed_end_date_front_door_4
                      - type: divider
                      - input_boolean.thu_front_door_4
                      - input_boolean.thu_inc_front_door_4
                      - input_datetime.thu_start_date_front_door_4
                      - input_datetime.thu_end_date_front_door_4
                      - type: divider
                      - input_boolean.fri_front_door_4
                      - input_boolean.fri_inc_front_door_4
                      - input_datetime.fri_start_date_front_door_4
                      - input_datetime.fri_end_date_front_door_4
                      - type: divider
                      - input_boolean.sat_front_door_4
                      - input_boolean.sat_inc_front_door_4
                      - input_datetime.sat_start_date_front_door_4
                      - input_datetime.sat_end_date_front_door_4
      - type: vertical-stack
        cards:
          - content: |
              ## Code 5
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_5
              - entity: input_text.front_door_pin_5
              - entity: input_boolean.enabled_front_door_5
              - entity: input_boolean.notify_front_door_5
              - type: divider
              - entity: sensor.connected_front_door_5
                state_color: true
              - entity: binary_sensor.active_front_door_5
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_5
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_5
                  - entity: input_number.accesscount_front_door_5
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_5
                  - entity: input_datetime.start_date_front_door_5
                  - entity: input_datetime.end_date_front_door_5
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_front_door_5
                      - input_boolean.sun_inc_front_door_5
                      - input_datetime.sun_start_date_front_door_5
                      - input_datetime.sun_end_date_front_door_5
                      - type: divider
                      - input_boolean.mon_front_door_5
                      - input_boolean.mon_inc_front_door_5
                      - input_datetime.mon_start_date_front_door_5
                      - input_datetime.mon_end_date_front_door_5
                      - type: divider
                      - input_boolean.tue_front_door_5
                      - input_boolean.tue_inc_front_door_5
                      - input_datetime.tue_start_date_front_door_5
                      - input_datetime.tue_end_date_front_door_5
                      - type: divider
                      - input_boolean.wed_front_door_5
                      - input_boolean.wed_inc_front_door_5
                      - input_datetime.wed_start_date_front_door_5
                      - input_datetime.wed_end_date_front_door_5
                      - type: divider
                      - input_boolean.thu_front_door_5
                      - input_boolean.thu_inc_front_door_5
                      - input_datetime.thu_start_date_front_door_5
                      - input_datetime.thu_end_date_front_door_5
                      - type: divider
                      - input_boolean.fri_front_door_5
                      - input_boolean.fri_inc_front_door_5
                      - input_datetime.fri_start_date_front_door_5
                      - input_datetime.fri_end_date_front_door_5
                      - type: divider
                      - input_boolean.sat_front_door_5
                      - input_boolean.sat_inc_front_door_5
                      - input_datetime.sat_start_date_front_door_5
                      - input_datetime.sat_end_date_front_door_5
      - type: vertical-stack
        cards:
          - content: |
              ## Code 6
            type: markdown
          - type: entities
            show_header_toggle: false
            entities:
              - entity: input_text.front_door_name_6
              - entity: input_text.front_door_pin_6
              - entity: input_boolean.enabled_front_door_6
              - entity: input_boolean.notify_front_door_6
              - type: divider
              - entity: sensor.connected_front_door_6
                state_color: true
              - entity: binary_sensor.active_front_door_6
                state_color: true
              - type: 'custom:fold-entity-row'
                head:
                  type: section
                  label: Advanced Options
                entities:
                  - entity: input_boolean.reset_codeslot_front_door_6
                  - type: divider
                  - entity: input_boolean.accesslimit_front_door_6
                  - entity: input_number.accesscount_front_door_6
                    type: 'custom:numberbox-card'
                    icon: 'mdi:key-variant'
                    speed: 250
                  - type: divider
                  - entity: input_boolean.daterange_front_door_6
                  - entity: input_datetime.start_date_front_door_6
                  - entity: input_datetime.end_date_front_door_6
                  - type: 'custom:fold-entity-row'
                    head:
                      type: section
                      label: Custom Weekdays
                    entities:
                      - input_boolean.sun_front_door_6
                      - input_boolean.sun_inc_front_door_6
                      - input_datetime.sun_start_date_front_door_6
                      - input_datetime.sun_end_date_front_door_6
                      - type: divider
                      - input_boolean.mon_front_door_6
                      - input_boolean.mon_inc_front_door_6
                      - input_datetime.mon_start_date_front_door_6
                      - input_datetime.mon_end_date_front_door_6
                      - type: divider
                      - input_boolean.tue_front_door_6
                      - input_boolean.tue_inc_front_door_6
                      - input_datetime.tue_start_date_front_door_6
                      - input_datetime.tue_end_date_front_door_6
                      - type: divider
                      - input_boolean.wed_front_door_6
                      - input_boolean.wed_inc_front_door_6
                      - input_datetime.wed_start_date_front_door_6
                      - input_datetime.wed_end_date_front_door_6
                      - type: divider
                      - input_boolean.thu_front_door_6
                      - input_boolean.thu_inc_front_door_6
                      - input_datetime.thu_start_date_front_door_6
                      - input_datetime.thu_end_date_front_door_6
                      - type: divider
                      - input_boolean.fri_front_door_6
                      - input_boolean.fri_inc_front_door_6
                      - input_datetime.fri_start_date_front_door_6
                      - input_datetime.fri_end_date_front_door_6
                      - type: divider
                      - input_boolean.sat_front_door_6
                      - input_boolean.sat_inc_front_door_6
                      - input_datetime.sat_start_date_front_door_6
                      - input_datetime.sat_end_date_front_door_6
```
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/29254374/211699312-b515fe4b-aaa5-4f6a-b2aa-fae28e49249d.png">
