### ISSUE TITLE
ISSUE: Cannot get notifications to work.

### ISSUE THREAD

**Issue by joeinaustin** [FutureTense/keymaster#317]
**Describe the bug**
No form of notification works from keymaster. I followed the wiki instuctions and used the code example for my scripts.yaml.  I can manually create different types of notifications from dev tools, but nothing is ever generated from keymaster.  I do see lock status updates in the history and noticiation is turned on for all active codes.  Nothing showing up in the logs at all.  What else can I look at???

**Environment (please complete the following information):**

- OS: Latest as of 1-16-22
- Type of system that HA is running on: NUC
- Home Assistant version: [e.g. 0.105.5]
- Hassio/Docker/Core?
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: zwave_js
- Lock make and model: Schlage
Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

**Logs**
Nothing relevant to paste

**Screenshots**
Let me know which would help

I did add a second script (see below) in case my naming conventions were off.  I found some docs online that show it with a keymaster prefix.  That was no help.

```
front_lock_manual_notify:
  mode: parallel
  sequence:
    - service: notify.notify
      data:
        title: "{{ title }}"
        message: "{{ message }}"
# created dup of above to to unclear naming conventions
keymaster_front_lock_manual_notify:
  mode: parallel
  sequence:
    - service: notify.notify
      data:
        title: "{{ title }}"
        message: "{{ message }}"
```
