### ISSUE TITLE
ISSUE: Keymaster events are not being fired anymore 

### ISSUE THREAD

**Issue by dougmaitelli** [FutureTense/keymaster#348]
**Describe the bug**
I have a listener that checked for Keymaster events and notifies me about who unlocked the door using code. This event always worked perfectly but on December 19th it stopped working. I am not sure what was updated at that date, probably either home assistant or zwave itself.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: Proxmox
- Home Assistant version: 2023.12.3
- Hassio/Docker/Core? HassOS
- Component version: latest
- Z-Wave integration name: zwave_js
- Lock make and model: Yale Assure Lock 2

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by firstof9** [comment]
I just tested it, it's working fine for me:

```yaml
event_type: keymaster_lock_state_changed
data:
  notification_source: event
  lockname: frontdoor
  entity_id: lock.front_door
  state: locked
  action_text: Manual lock operation
  code_slot: 0
  code_slot_name: ""
origin: LOCAL
time_fired: "2023-12-27T20:07:47.913850+00:00"
context:
  id: 01HJPE7VE9PXQ09GK3XFFRRKEZ
  parent_id: null
  user_id: null
```
