### ISSUE TITLE
[Feature Request] Any chance keymaster could be extended to use the "hubitat" integration in addition to Z-Wave?

### ISSUE THREAD

**Issue by irvintim** [FutureTense/keymaster#352]
**Is your feature request related to a problem? Please describe.**
I'd love to use `keymaster` to control the lock codes, but I don't use a Z-Wave stick on the HA box. I instead have Hubitat controllers installed around the property and use their Z-Wave antennas to communicate with the locks.  I use the "HA->Hubitat" integration to get data and control the locks.

**Describe the solution you'd like**
The hubitat integration provides these services to control the locks (from: https://github.com/jason0x43/hacs-hubitat). It would be great if they could be substituted for the equivalent Z-Wave commands.

> This integration adds several service calls to Home Assistant.

- Delete the alarm code at a given position in a lock or keypad

```
service: hubitat.clear_code
data:
  entity_id: lock.some_lock
  position: 1
```
- Set a user code for a lock or keypad
```
service: hubitat.set_code
data:
  entity_id: lock.some_lock
  position: 1
  code: 5213
  name: Guests
```
- Set the length of user codes for a lock or keypad
```
service: hubitat.set_code_length
data:
  entity_id: lock.some_lock
  length: 4
```
- Set the entry delay for a security keypad in seconds
```
service: hubitat.set_entry_delay
data:
  entity_id: alarm_control_panel.some_alarm
  delay: 30
```

**Describe alternatives you've considered**
I don't have a Z-Wave device on my HA box for a few reasons; mostly, the locks don't seem to work well through the mesh and work MUCH better when a Hubitat node is set up close to the lock.  Also, this allows me to have a redundant HA integration without worrying about swapping the Z-Wave stick on failover.
I want to use the `Rental Control` integration to sync my vacation rental calendar with the locks, and that integration uses `keymaster` to control the locks.

**Additional context**
I started to look at the code to see what would be involved but have yet to dig in too deeply. I'm happy to take a crack at this and submit a PR, but I could use a little pointer; I have yet to do any Home Assistant programming, so I'm unfamiliar with the libraries.
