### ISSUE TITLE
Categories require automation ids

### ISSUE THREAD

**Issue by roblandry** [FutureTense/keymaster#360]
For some reason, starting with [L386](https://github.com/FutureTense/keymaster/blob/f4f1046bddb7901cbd3ce7820886be1ff7895fe7/custom_components/keymaster/keymaster_child.yaml#L386), automation ids stopped being included. 
```yaml
  - alias: keymaster_copy_PARENTLOCK_sun_LOCKNAME_TEMPLATENUM
    trigger:
      ...
```

In order to add to categories and clean up automations, this is required. Please update to include ids like the previous automations: [L370](https://github.com/FutureTense/keymaster/blob/f4f1046bddb7901cbd3ce7820886be1ff7895fe7/custom_components/keymaster/keymaster_child.yaml#L370)

```yaml
  - alias: keymaster_copy_PARENTLOCK_end_date_LOCKNAME_TEMPLATENUM
    id: keymaster_copy_PARENTLOCK_end_date_LOCKNAME_TEMPLATENUM
    trigger:
      ...
```
