### ISSUE TITLE
ISSUE: Unexpected error fetching keymaster data: 'node_id'

### ISSUE THREAD

**Issue by johnnyl6** [FutureTense/keymaster#66]
Using the latest version 0.0.7 but I think the const.py file still contains 0.0.6. 
Lock: schlage BE469

It seems that I can set PIN using lovelace UI and the status is connected. PIN also works for the door. However I am not getting any notifications from the door to my mobile app.

Only got one error in the log, maybe related to the notification issue?

Logger: custom_components.keymaster
Source: custom_components/keymaster/helpers.py:58
Integration: keymaster (documentation, issues)
First occurred: 4:18:17 PM (1 occurrences)
Last logged: 4:18:17 PM

Unexpected error fetching keymaster data: 'node_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 132, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/keymaster/__init__.py", line 420, in async_update_usercodes
    return await self.hass.async_add_executor_job(self.update_usercodes)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/keymaster/__init__.py", line 435, in update_usercodes
    node_id = get_node_id(self.hass, self._lock.lock_entity_id)
  File "/config/custom_components/keymaster/helpers.py", line 58, in get_node_id
    return state.attributes[ATTR_NODE_ID]
KeyError: 'node_id'

**Details from the log file:**

2021-01-29 16:34:53 INFO (MainThread) [custom_components.keymaster] Version 0.0.6 is starting, if you have any issues please report them here: https://github.com/FutureTense/keymaster
2021-01-29 16:35:00 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 1.961 seconds
2021-01-29 16:35:05 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.002 seconds
2021-01-29 16:35:10 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.134 seconds
2021-01-29 16:35:18 ERROR (MainThread) [custom_components.keymaster] Unexpected error fetching keymaster data: 'node_id'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 132, in _async_update_data
return await self.update_method()
File "/config/custom_components/keymaster/__init__.py", line 420, in async_update_usercodes
return await self.hass.async_add_executor_job(self.update_usercodes)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/keymaster/__init__.py", line 435, in update_usercodes
node_id = get_node_id(self.hass, self._lock.lock_entity_id)
File "/config/custom_components/keymaster/helpers.py", line 58, in get_node_id
return state.attributes[ATTR_NODE_ID]
KeyError: 'node_id'

**Comment by raman325** [comment]
Did you see any additional logs like the following after the error?
`2021-01-29 16:35:05 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.002 seconds`

If so then it's safe to ignore. Did you follow the wiki to set up notifications (https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script)? It doesn't happen automatically since we don't know where you want to target your notification

**Comment by johnnyl6** [comment]
Yes there are subsequent logs after which all look normal without errors.

I followed the wiki to have scripts.yaml which contains the following:

frontdoor_manual_notify:
  mode: parallel
  sequence:
    - service: notify.notify
      data:
        title: "{{ title }}"
        message: "{{ message }}"

I also verified the above script is working using the "developer tools" --> services to send notification. My mobile app can receive testing messages. 

I see many automations are created like "frontdoor Lock Notifications" "frontdoor Changed code". How to I configure these automation to send notifications?

**Comment by firstof9** [comment]
> I see many automations are created like "frontdoor Lock Notifications" "frontdoor Changed code". How to I configure these automation to send notifications?

They all get sent to the `frontdoor_manual_notify` script.
There should also be keymaster events that are fired off as well, you can watch these from the events tab in the dev-tools. You can use these to build notification automations as well.

**Comment by johnnyl6** [comment]
> > I see many automations are created like "frontdoor Lock Notifications" "frontdoor Changed code". How to I configure these automation to send notifications?
> 
> They all get sent to the `frontdoor_manual_notify` script.
> There should also be keymaster events that are fired off as well, you can watch these from the events tab in the dev-tools. You can use these to build notification automations as well.

Thanks for the clarification. I migrated to OpenZWave from the hassio native zwave integration. the error is gone. Everything works now except the lock notification. I had to enable some disabled entities and select them during keymaster configuration 
to make it work. My setup is below:

![image](https://user-images.githubusercontent.com/58282608/106375824-75c98880-6344-11eb-892b-1f861947dc3f.png)




I noticed there is a "frontdoor lock notification" can be turned on in lovelace UI, but it didn't help (still no notification). I even tried turning on the "frontdoor door notification" which relates to the door sensor, surprisingly it DOES send notification when door open/close. Any suggestions?



![image](https://user-images.githubusercontent.com/58282608/106375774-0bb0e380-6344-11eb-886c-376d49912a75.png)

**Comment by raman325** [comment]
Did you enable notifications on individual code slots? I just checked and I think the logic for the User Notification logic is hooked up to the individual code slot notification sensors instead of that one up top. So to get a notification for code slot 1, you turn that one on, code slot 2, etc.

I think we need to rethink the notification system a bit, it's a bit confusing

**Comment by johnnyl6** [comment]
> Did you enable notifications on individual code slots? I just checked and I think the logic for the User Notification logic is hooked up to the individual code slot notification sensors instead of that one up top. So to get a notification for code slot 1, you turn that one on, code slot 2, etc.
> 
> I think we need to rethink the notification system a bit, it's a bit confusing

Yes it's on for each pin slot. Is it possible to check the log how the notification are fired?

**Comment by raman325** [comment]
If you enable debug on automations, you should be able to see when the automation triggers and the fact that it should be calling your script.manual_notify script

**Comment by raman325** [comment]
what is the state of `input_boolean.allow_automation_execution` for you? I wonder if we are loading too late now to catch the event that flips that on

**Comment by firstof9** [comment]
Make sure you've created a notify script there's an [example in the wiki](https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script#example-notification-script).

**Comment by johnnyl6** [comment]
> what is the state of `input_boolean.allow_automation_execution` for you? I wonder if we are loading too late now to catch the event that flips that on

The state is on. Can you take a look at the following error? It's from my recent logs. I think it's related the the notification not fireing problem. I am running hassio core 2021.1.5

2021-01-31 14:39:44 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.021 seconds
**2021-01-31 14:39:46 ERROR (MainThread) [homeassistant.components.automation.frontdoor_lock_notifications] frontdoor Lock Notifications: Error executing script. Unexpected error for call_service at pos 1: Error rendering data template: UndefinedError: 'trigger' is undefined**
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
render_result = compiled.render(kwargs)
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 407, in getattr
value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'trigger' is undefined
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 188, in async_prepare_call_from_config
service_data.update(template.render_complex(config[conf], variables))
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 93, in render_complex
return {
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 94, in <dictcomp>
render_complex(key, variables): render_complex(item, variables)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 98, in render_complex
return value.async_render(variables)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'trigger' is undefined
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 429, in _async_call_service_step
domain, service_name, service_data = service.async_prepare_call_from_config(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 190, in async_prepare_call_from_config
raise HomeAssistantError(f"Error rendering data template: {ex}") from ex
homeassistant.exceptions.HomeAssistantError: Error rendering data template: UndefinedError: 'trigger' is undefined
2021-01-31 14:39:46 ERROR (MainThread) [homeassistant.components.automation.frontdoor_lock_notifications] While executing automation automation.frontdoor_lock_notifications
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
render_result = compiled.render(kwargs)
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 407, in getattr
value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'trigger' is undefined
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 188, in async_prepare_call_from_config
service_data.update(template.render_complex(config[conf], variables))
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 93, in render_complex
return {
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 94, in <dictcomp>
render_complex(key, variables): render_complex(item, variables)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 98, in render_complex
return value.async_render(variables)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'trigger' is undefined
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 404, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1026, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 242, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
await getattr(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 429, in _async_call_service_step
domain, service_name, service_data = service.async_prepare_call_from_config(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 190, in async_prepare_call_from_config
raise HomeAssistantError(f"Error rendering data template: {ex}") from ex
homeassistant.exceptions.HomeAssistantError: Error rendering data template: UndefinedError: 'trigger' is undefined
2021-01-31 14:39:49 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 257 value: 30
2021-01-31 14:39:49 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 255 value: False
2021-01-31 14:39:49 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 256 value: 0
2021-01-31 14:39:49 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 0 value:
2021-01-31 14:39:49 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 1 value: **********
2021-01-31 14:39:49 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Ignoring code slot with * in value.
2021-01-31 14:39:49 DEBUG (SyncWorker_0) [custom_components.keymaster] Work around code in use.

**Comment by raman325** [comment]
can you open the frontdoor_keymaster_common file and find that automation YAML and paste it here?

**Comment by johnnyl6** [comment]
Here you go:

```yaml
###################  automation:  ####################
automation:

  - alias: reset_codeslot_frontdoor
    trigger:
      entity_id: input_boolean.reset_codeslot_frontdoor_1,input_boolean.reset_codeslot_frontdoor_2,input_boolean.reset_codeslot_frontdoor_3,input_boolean.reset_codeslot_frontdoor_4,input_boolean.reset_codeslot_frontdoor_5,input_boolean.reset_codeslot_frontdoor_6,input_boolean.reset_codeslot_frontdoor_7,input_boolean.reset_codeslot_frontdoor_8,input_boolean.reset_codeslot_frontdoor_9,input_boolean.reset_codeslot_frontdoor_10
      platform: state
      to: 'on'
    action:
      - service: script.frontdoor_reset_codeslot
        data_template:
          code_slot: "{{ trigger.entity_id.split('_')[-1] }}"

  - alias: frontdoor Lock Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: frontdoor
    condition:
      - condition: state
        entity_id: "input_boolean.allow_automation_execution"
        state: "on"
    action:
      - service: script.frontdoor_conditional_notify
        data_template:
          boolean: input_boolean.frontdoor_lock_notifications
          title: frontdoor
          message: "{{ trigger.event.data.action_text }}"

  - alias: frontdoor User Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: frontdoor
    condition:
      - condition: state
        entity_id: "input_boolean.allow_automation_execution"
        state: "on"
      - condition: template
        value_template: "{{ trigger.event.data.code_slot > 0 }}"
      - condition: template
        value_template: "{{ is_state('input_boolean.notify_frontdoor_' + trigger.event.data.code_slot | string, 'on') }}"
    action:
      - service: script.frontdoor_manual_notify
        data_template:
          title: "{{ trigger.event.data.action_text }}"
          message: "{{ trigger.event.data.code_slot_name }}"

  - alias: frontdoor Sensor Close
    condition:
      - condition: state
        entity_id: "input_boolean.allow_automation_execution"
        state: "on"
    trigger:
      entity_id: binary_sensor.front_door
      platform: state
      to: "off"
    action:
      - service: script.frontdoor_conditional_notify
        data_template:
          boolean: input_boolean.frontdoor_dooraccess_notifications
          title: frontdoor
          message: "Closed"

  - alias: frontdoor Sensor Opened
    condition:
      - condition: state
        entity_id: "input_boolean.allow_automation_execution"
        state: "on"
    trigger:
      entity_id: binary_sensor.front_door
      platform: state
      to: "on"
    action:
      - service: script.frontdoor_conditional_notify
        data_template:
          boolean: input_boolean.frontdoor_dooraccess_notifications
          title: frontdoor
          message: "Opened"

  - alias: frontdoor Changed Code
    trigger:
      entity_id: input_text.frontdoor_pin_1,input_text.frontdoor_pin_2,input_text.frontdoor_pin_3,input_text.frontdoor_pin_4,input_text.frontdoor_pin_5,input_text.frontdoor_pin_6,input_text.frontdoor_pin_7,input_text.frontdoor_pin_8,input_text.frontdoor_pin_9,input_text.frontdoor_pin_10
      platform: state
    condition:
      - condition: state
        entity_id: "input_boolean.allow_automation_execution"
        state: "on"
      - condition: template
        value_template: >-
          {{
            is_state('input_boolean.frontdoor_enabled_' + trigger.entity_id.split('_')[-1], 'on')
            and
            (trigger.from_state.state != trigger.to_state.state)
          }}
    action:
      - service: persistent_notification.create
        data_template:
          title: frontdoor LOCK MANAGER
          message: >-
            {{ 'You changed the PIN for frontdoor code slot ' + trigger.entity_id.split('_')[-1] + '. Please enable it in order to make it active.'}}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {{ 'input_boolean.enabled_frontdoor_' + trigger.entity_id.split('_')[-1] }}

  - alias: frontdoor Reset
    condition:
      - condition: state
        entity_id: "input_boolean.allow_automation_execution"
        state: "on"
    trigger:
      entity_id: input_boolean.frontdoor_reset_lock
      platform: state
      from: "off"
      to: "on"
    action:
      - service: script.frontdoor_reset_lock
      - service: input_boolean.turn_off
        entity_id: input_boolean.frontdoor_reset_lock

  - alias: frontdoor Decrement Access Count
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: frontdoor
    condition:
      - condition: state
        entity_id: "input_boolean.allow_automation_execution"
        state: "on"
      - condition: template
        # make sure decrementing access entries is enabled 
        value_template: "{{ is_state('input_boolean.accesslimit_frontdoor_' + trigger.event.data.code_slot | string, 'on') }}"
      - condition: template
        # Check for Keypad Unlock code
        value_template: "{{ trigger.event.data.code_slot > 0 and trigger.event.data.action_code in (6, 19)}}"
    action:
      - service: input_number.decrement
        data_template:
          entity_id: "{{ 'input_number.accesscount_frontdoor_' + trigger.event.data.code_slot | string }}"
```
